[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/medication.py"
name = "Medication"
icon = "ğŸ’Š"

[[pages]]
path = "pages/routine.py"
name = "Schedule"
icon = "ğŸ—“ï¸"

[[pages]]
path = "pages/events.py"
name = "Events"
icon = "ğŸ“†"

[[pages]]
path = "pages/settings.py"
name = "Settings"
icon = "âš™ï¸"