[[pages]]
name = "Main Menu"
icon = "ğŸ“Œ"
is_section = true

[[pages]]
path = "pages/menu.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/medication.py"
name = "Medication"
icon = "ğŸ’Š"

[[pages]]
path = "pages/routine.py"
name = "Routine"
icon = "ğŸ—“ï¸"

[[pages]]
path = "pages/events.py"
name = "Events"
icon = "ğŸ“†"

[[pages]]
name = "Others"
icon = "ğŸ”§"
is_section = true

[[pages]]
path = "pages/settings.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "pages/admin.py"
name = "Admin"
icon = "ğŸ› ï¸"